era5_path: data/Era5_GRIB_NEW_dataset_2023-2019_and_more_future
merged_data_path: data/merged_dataset.csv
pv_database_path: data/pv_database.csv
results_path: results
smarts_inp_path: data/smarts_inp_files
smarts_out_path: data/smarts_out_files
shapefile_path: data/koppen_shapefile.shp
DATA_FOLDER: data
MODEL_PATH: models
DB_PATH: data/database.sqlite
OUTPUT_DIR: outputs
train_features: "path/to/X_train.npy"
test_features: "path/to/X_test.npy"
train_target_pv: "path/to/y_train_pv.npy"
test_target_pv: "path/to/y_test_pv.npy"
train_target_cooling: "path/to/y_train_cooling.npy"
test_target_cooling: "path/to/y_test_cooling.npy"
train_target_net: "path/to/y_train_net.npy"
test_target_net: "path/to/y_test_net.npy"
use_kg_features: true
clustered_data_paths:
pv: results/clustered_predicted_pv.csv
rc: results/clustered_predicted_rc.csv
  combined: results/clustered_predicted_pv_rc_combined.csv

columns:
  lat: latitude
  lon: longitude
  cluster_id: Cluster_ID
  rc_cluster: RC_Cluster
  pv_tech: Best_Technology
  rc_potential: RC_potential
  p_rc_basic: P_rc_basic
  p_rc_net: P_rc_net
  t_air: T_air
  ghi: GHI
  rh: RH
  cloud_cover: TCC
  red_band: Red_band
  season: season
  year: year
